### ISSUE TITLE
Translate for Patreon

### ISSUE THREAD

**Issue by bmagic** [warcraftlfg/warcraft-lfg#303]
Can you translate / improve the following text for patreon ? 

**Tell your patrons why they should pledge to you**
FR: 
https://www.warcraftlfg.com
Warcraftlfg est un outil permettant de faciliter le recrutement de joueurs dans les guildes, il se base sur les sites déjà bien connus de la communauté (Warcraftlogs & WowProgress) en important les données de ces sites (statistiques, classements et annonces).

Warcraftlfg est cependant développé par des passionnés, nous aimons ce que nous faisons et nous voulons continuer à le faire sur notre temps libre et bénévolement.
Convaincu par le monde libre, l'ensemble de notre code est disponible sur Github en opensource avec une license AGPL3.

Cependant l'hébergement de ce service a un coût et nous souhaitons via ce patreon nous permettre de ne pas le supporter tout seul. 

Nous hébergeons le service chez OVH (https://www.soyoustart.com/us/offers/sys-ip-1.xml) nous avons donc besoin de 36€/42$ par mois soit 432€/504$ par an

En supportant Warcraftlfg vous permettrez à ce service de continuer.

**Reward Text** 1$ 
FR : Your name will be write on the Hall of Fame page of warcraftlfg website
EN : Votre nom sera écrit sur la page du mur des célébrités.

**Thank You Message**
FR : Merci de votre contribution, votre support nous fait chaud au cœur !! 
EN : Thanks for your support, this make us feel good.

**Comment by daleadae** [comment]
EN: 
https://www.warcraftlfg.com
Warcraftlfg strives to help guilds and players finding each others based on data (stats, progress etc) provided by popular community sites such as Warcraftlogs and WowProgress 

Warcraftlfg has been developed and maintain by a few passionate people, enjoying what they do and using most of their free time to provide this tool to the community, for free. We are supporter of open source softwares, which is why our codes are availlable on Github, using a AGPL3 license. 

Hosting such a website though is costly, and by launching this patreon we simply would like to help you help us supporting this service. 

Our servers (via OVH - https://www.soyoustart.com/us/offers/sys-ip-1.xml) cost us 36€/42$ per month. (432€/504$ per year) which is what we would ideally achieve.

Supporting Warcraftlfg will allow us to maintain this service for many years to come.
